language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

# safelist
branches:
  only:
  - master
  - develop

cache:
  directories:
    - node_modules

addons:
  chrome: stable

install:
  - npm install -g yarn

script:
  - yarn
  - yarn lint
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/workboxpwa
  on:
    branch: master